x-shovel-service: &shovel-service
  depends_on:
    clickhouse:
      condition: service_started
  env_file:
    - .env
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"
  networks:
    - app_network
  restart: on-failure
  extra_hosts:
    - "host.docker.internal:host-gateway"
  tty: true

services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.5.5.36-alpine
    container_name: clickhouse
    ports:
      - "8123:8123" # HTTP interface for ClickHouse
      - "9000:9000" # Native client interface for ClickHouse
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - app_network
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    restart: on-failure

  shovel_block_timestamp:
    <<: *shovel-service
    build:
      context: ./scraper_service
      dockerfile: ./Dockerfile
      args:
        SERVICE_NAME: shovel_block_timestamp
    container_name: shovel_block_timestamp

  shovel_extrinsics:
    <<: *shovel-service
    build:
      context: ./scraper_service
      dockerfile: ./Dockerfile
      args:
        SERVICE_NAME: shovel_extrinsics
    container_name: shovel_extrinsics

  shovel_events:
    <<: *shovel-service
    build:
      context: ./scraper_service
      dockerfile: ./Dockerfile
      args:
        SERVICE_NAME: shovel_events
    container_name: shovel_events

  shovel_stake_map:
    <<: *shovel-service
    build:
      context: ./scraper_service
      dockerfile: ./Dockerfile
      args:
        SERVICE_NAME: shovel_stake_map
    container_name: shovel_stake_map

  shovel_hotkey_owner_map:
    <<: *shovel-service
    build:
      context: ./scraper_service
      dockerfile: ./Dockerfile
      args:
        SERVICE_NAME: shovel_hotkey_owner_map
    container_name: shovel_hotkey_owner_map

  shovel_subnets:
    <<: *shovel-service
    build:
      context: ./scraper_service
      dockerfile: ./Dockerfile
      args:
        SERVICE_NAME: shovel_subnets
    container_name: shovel_subnets
    restart: always

  shovel_daily_stake:
    <<: *shovel-service
    build:
      context: ./scraper_service
      dockerfile: ./Dockerfile
      args:
        SERVICE_NAME: shovel_daily_stake
    container_name: shovel_daily_stake

  shovel_daily_balance:
    <<: *shovel-service
    build:
      context: ./scraper_service
      dockerfile: ./Dockerfile
      args:
        SERVICE_NAME: shovel_daily_balance
    container_name: shovel_daily_balance

  shovel_tao_price:
    <<: *shovel-service
    build:
      context: ./scraper_service
      dockerfile: ./Dockerfile
      args:
        SERVICE_NAME: shovel_tao_price
    container_name: shovel_tao_price

  shovel_alpha_to_tao:
    <<: *shovel-service
    build:
      context: ./scraper_service
      dockerfile: ./Dockerfile
      args:
        SERVICE_NAME: shovel_alpha_to_tao
    container_name: shovel_alpha_to_tao

  # Validators service needs special handling due to Rust requirements
  shovel_validators:
    <<: *shovel-service
    build:
      context: ./scraper_service
      dockerfile: ./Dockerfile.validators
    container_name: shovel_validators

  # shovel_balance_map:
  #   <<: *shovel-service
  #   build:
  #     context: ./scraper_service
  #     dockerfile: ./Dockerfile
  #     args:
  #       SERVICE_NAME: shovel_balance_map
  #   container_name: shovel_balance_map

volumes:
  clickhouse_data:

networks:
  app_network:
